20181120




(myenv) seiji@xbnt16:~/myproject$ pip install PyMySQL
Collecting PyMySQL
  Downloading https://files.pythonhosted.org/packages/a7/7d/682c4a7da195a678047c8f1c51bb7682aaedee1dca7547883c3993ca9282/PyMySQL-0.9.2-py2.py3-none-any.whl (47kB)
    100% |████████████████████████████████| 51kB 724kB/s 
Collecting cryptography (from PyMySQL)
  Downloading https://files.pythonhosted.org/packages/01/79/65e25dfee3eaf4c9bbebac2925d904eb8f59cceafa7014fb2f883b1ea055/cryptography-2.4.1-cp34-abi3-manylinux1_i686.whl (1.9MB)
    100% |████████████████████████████████| 1.9MB 783kB/s 
Collecting idna>=2.1 (from cryptography->PyMySQL)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.7 (from cryptography->PyMySQL)
  Using cached https://files.pythonhosted.org/packages/f9/2a/c6ef0d6ddfbec86e61360995de7c51251333c31213dc30cee7441d94396a/cffi-1.11.5-cp36-cp36m-manylinux1_i686.whl
Collecting asn1crypto>=0.21.0 (from cryptography->PyMySQL)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography->PyMySQL)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography->PyMySQL)
Installing collected packages: idna, pycparser, cffi, asn1crypto, six, cryptography, PyMySQL
Successfully installed PyMySQL-0.9.2 asn1crypto-0.24.0 cffi-1.11.5 cryptography-2.4.1 idna-2.7 pycparser-2.19 six-1.11.0
(myenv) seiji@xbnt16:~/myproject$ 



Python3 + django から　MySQl への接続設定
---------------------------------------------------------------------------

* mysiteに関連付ける前の状態。

mysql> SHOW DATABASES;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| employees          |
| mysql              |
| performance_schema |
| phpmyadmin         |
| sys                |
+--------------------+
6 rows in set (0.67 sec)

mysql> 

--------------------------------------------------------
mysql> CREATE DATABASE djangoDb;
Query OK, 1 row affected (0.41 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| djangoDb           |
| employees          |
| mysql              |
| performance_schema |
| phpmyadmin         |
| sys                |
+--------------------+
7 rows in set (0.00 sec)


mysql> CREATE USER seiji01 IDENTIFIED BY 'FLWgar#3$4';
Query OK, 0 rows affected (0.83 sec)


mysql> grant all on djangoDb.* to 'seiji'@'localhost' identified by 'xxxzzzy
yy';
Query OK, 0 rows affected, 1 warning (0.37 sec)


mysql> use djangoDb;
Database changed
mysql> select host, user from mysql.user;
+-----------+------------------+
| host      | user             |
+-----------+------------------+
| %         | seiji            |
| %         | seiji01          |
| localhost | debian-sys-maint |
| localhost | mysql.session    |
| localhost | mysql.sys        |
| localhost | phpmyadmin       |
| localhost | root             |
| localhost | seiji            |
+-----------+------------------+
8 rows in set (0.01 sec)



mysql> show grants for 'seiji01'@'localhost';
ERROR 1141 (42000): There is no such grant defined for user 'seiji01' on host 'localhost'
mysql> show grants for 'seiji'@'localhost';
+-------------------------------------------------------------+
| Grants for seiji@localhost                                  |
+-------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'seiji'@'localhost'                   |
| GRANT ALL PRIVILEGES ON `djangoDb`.* TO 'seiji'@'localhost' |
+-------------------------------------------------------------+
2 rows in set (0.00 sec)

mysql> revoke all privileges, grant option from 'seiji'@'localhost';
Query OK, 0 rows affected (0.38 sec)


seijiの権限を削除して、改めてseiji01のdjangoDbへの権限付与。
---------------------------------------------------s
mysql> grant all on djangoDb.* to 'seiji01'@'localhost' identified by '
xxxyyyzzz;
Query OK, 0 rows affected, 1 warning (0.02 sec)


mysql> show grants for 'seiji01'@'localhost';
+---------------------------------------------------------------+
| Grants for seiji01@localhost                                  |
+---------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'seiji01'@'localhost'                   |
| GRANT ALL PRIVILEGES ON `djangoDb`.* TO 'seiji01'@'localhost' |
+---------------------------------------------------------------+
2 rows in set (0.00 sec)









---------------------------------------------------------------------------
pipでpymysqlインストール後、manage.pyを以下のように編集する。


#!/usr/bin/env python
import os
import sys

if __name__ == '__main__':
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mysite.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)
~                                         
-----------------------------------------------
#!/usr/bin/env python
import os
import sys
import pymysql

pymysql.install_as_MySQL()

;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;


----------------------------------------------------------------------------
(myenv) seiji@xbnt16:~/myproject/mysite$ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
/home/seiji/myproject/myenv/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (3135, "'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.")
  result = self._query(query)
/home/seiji/myproject/myenv/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (3090, "Changing sql mode 'NO_AUTO_CREATE_USER' is deprecated. It will be removed in a future release.")
  result = self._query(query)

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

November 21, 2018 - 16:25:28
Django version 2.1.3, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
^C(myenv) seiji@xbnt16:~/myproject/mysite$ 











































































